name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js (Latest LTS)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Copy to index.html for GitHub Pages
      run: cp kindle-notes-web-app.html index.html

    - name: Verify build output
      run: |
        if [ ! -f "index.html" ]; then
          echo "Build failed: index.html not found"
          exit 1
        fi
        echo "Build successful: $(ls -lh index.html)"
        echo "Original file: $(ls -lh kindle-notes-web-app.html)"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: kindle-notes-index
        path: index.html